train_config_path: src/config/train/flat_dense_triplet_30fps.yml
test_config_path: src/config/test/mabe.yml
baseline_config_path: src/config/benchmark/motion_baselines_30fps_pred12.yml
checkpoint_path: checkpoints/flat_dense_triplet_30fps/flat_best.pt
results_path: outputs/evaluations/flat_dense_triplet_30fps/benchmark_8_12/results.jsonl
model_name: social_attention_flat_dense_triplet_30fps
