train_config_path: src/config/train/flat_within_mouse_triplet_5fps.yml
test_config_path: src/config/test/mabe.yml
baseline_config_path: src/config/benchmark/motion_baselines_5fps_pred24.yml
checkpoint_path: checkpoints/flat_within_mouse_triplet_5fps/flat_best.pt
results_path: outputs/evaluations/flat_within_mouse_triplet_5fps/benchmark_16_24/results.jsonl
model_name: social_attention_flat_within_mouse_triplet_5fps
