"""File description: Experiment and runtime configuration."""

from config.mabe import (
    COORDINATES,
    DEFAULT_OBSERVATION_LENGTH,
    DEFAULT_PREDICTION_LENGTH,
    DEFAULT_SEQUENCE_LENGTH,
    DEFAULT_SPLIT_SEED,
    DEFAULT_VALIDATION_FRACTION,
    DEFAULT_WINDOW_STRIDE,
    FRAME_HEIGHT,
    FRAME_WIDTH,
    KEYPOINT_NAMES,
    NUM_KEYPOINTS,
    NUM_MICE,
)

__all__ = [
    "COORDINATES",
    "DEFAULT_OBSERVATION_LENGTH",
    "DEFAULT_PREDICTION_LENGTH",
    "DEFAULT_SEQUENCE_LENGTH",
    "DEFAULT_SPLIT_SEED",
    "DEFAULT_VALIDATION_FRACTION",
    "DEFAULT_WINDOW_STRIDE",
    "FRAME_HEIGHT",
    "FRAME_WIDTH",
    "KEYPOINT_NAMES",
    "NUM_KEYPOINTS",
    "NUM_MICE",
]
